apiVersion: v1
kind: Service
metadata:
  labels:
    name: backendspring
  name: backendspring
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    app: backendspring
