apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendspring
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backendspring
  template:
    metadata:
      labels:
        app: backendspring
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        name: backendspring
        ports:
        - name: backendspring
          containerPort: 8080
        env:
      
